config_id: config_red

# AUDIO
sample_rate: 22050
n_fft: 2048
n_mels: 80
win_length: 1100
hop_length: 275
fmin: 40
min_db: -100
ref_db: 20

# PREPROCESSING
n_workers: 16

# TEXT
symbols: "!'(),.:;?_- ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜäöüabcdefghijklmnopqrstuvwxyz"
cleaners: 'english_cleaners'

# DATASET
seed: 42
n_val: 100
max_mel_len: 1200

# TRAINING (overrides loaded model config)
training_schedule:
  - [10, 1e-3, 5_000, 4]
  - [5,  1e-4, 10_000, 8]
  - [2,  1e-4, 30_000, 8]
log_dir: /tmp/tacogan
steps_to_eval: 10
steps_to_checkpoint: 1_000
silence_len: 50 # extra mel steps with silence as stopping criterion


# MODEL
embed_dims: 16
encoder_dims: 128
decoder_dims: 256
postnet_dims: 128
encoder_K: 2
lstm_dims: 16
postnet_K: 2
num_highways: 4
dropout: 0.5
stop_threshold: -3.4


# GAN PARAMS
gan_conv_dim: 256
gan_rnn_dim: 256
gan_dropout: 0.5
