# AUDIO
sample_rate: 22050
n_fft: 2048
n_mels: 80
win_length: 1100
hop_length: 275
fmin: 40
min_db: -100
ref_db: 20

# PREPROCESSING
n_workers: 16

# TEXT
symbols: "!'(),.:;?_- ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜäöüabcdefghijklmnopqrstuvwxyz"
cleaners: 'english_cleaners'

# GENERAL
seed: 42

# DATASET
n_val: 200
max_mel_len: 1200

# TRAINING
training_schedule:
  - [10, 1e-3, 10, 32]
  - [5, 1e-4, 20, 8]
  - [2, 1e-4, 30, 8]
