# AUDIO
sample_rate: 22050
n_fft: 2048
n_mels: 80
win_length: 1100
hop_length: 275
fmin: 40
min_db: -100
ref_db: 20

# PREPROCESSING
n_workers: 16

# TEXT
letters: !\'(),.:;?_- ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜäöüabcdefghijklmnopqrstuvwxyz