config_id: ljspeech_2

# AUDIO
sample_rate: 22050
n_fft: 2048
n_mels: 80
win_length: 1024
hop_length: 256
fmin: 0
fmax: 8000

# PREPROCESSING
n_workers: 16

# TEXT
language: "en"
cleaners: 'english_cleaners'
symbols: "!'(),.:;?- ˈˌːˑiyɨʉɯuɪʏʊeøɘəɵɤoɛœɜɞʌɔæɐaɶɑɒᵻʘɓǀɗǃʄǂɠǁʛpbtdʈɖcɟkɡqɢʔɴŋɲɳnɱmʙrʀⱱɾɽɸβfvθðszʃʒʂʐçʝxɣχʁħʕhɦɬɮʋɹɻjɰlɭʎʟʍwɥʜʢʡɕʑɺɧɚ˞ɫ"

# DATASET
seed: 42
n_val: 100
max_mel_len: 1200

# TRAINING FORWARD (overrides loaded model config)
forward_training_schedule:
  - [1e-4, 5_000, 8]
  - [1e-4, 10_000, 32]
  - [1e-4, 30_000, 32]
forward_steps_to_eval: 5
forward_steps_to_plot: 5
forward_steps_to_checkpoint: 1_000


# TRAINING ALIGNER (overrides loaded model config)
aligner_training_schedule:
  - [1e-4, 100_000, 8]
aligner_steps_to_eval: 500
aligner_steps_to_checkpoint: 10




# FORWARD PARAMS
embed_dims: 256
durpred_conv_dims: 256
durpred_rnn_dims: 64
durpred_dropout: 0.5
rnn_dim: 256
prenet_k: 16
prenet_dims: 256
postnet_k: 8
postnet_dims: 256
highways: 4
dropout: 0.1

# ALIGNER PARAMS
aligner_lstm_dim: 256
aligner_conv_dim: 256
aligner_dropout: 0
